name: seed
description: "Smart Agriculture"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.2
  provider: ^6.0.4
  shared_preferences: ^2.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/images/google_logo.png
