name: seed
description: "Smart Agriculture"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  convex_bottom_bar: ^3.2.0
  intl: ^0.18.1
  flutter_svg: ^2.0.17
  xml: ^6.5.0
  path_drawing: ^1.0.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.4
  provider: ^6.1.2
  shared_preferences: ^2.0.18
  flutter_native_splash: ^2.4.4
  tflite_flutter: ^0.11.0
  lottie: ^3.2.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter_native_splash:
  color: "#ffffff"  # Background color of the splash screen
  image: assets/images/logo.png  # Path to your splash image
    color: "#2596be"  # Background color
    image: assets/images/seed10.png
    android_12:
      image: assets/images/seed10.png
      color: "#2596be"


flutter:
  uses-material-design: true

  assets:
     - assets/images/google_logo.png
     - assets/images/seed.jpg
     - assets/weather/clear.jpg
     - assets/weather/rain.jpg
     - assets/weather/cloudy.jpg
     - assets/images/chatbot1.png
     - assets/images/chat.png
     - assets/images/seed10.png
     - assets/crop_predict/ensemble_model.tflite
     - assets/crop_predict/labels.txt
     - assets/images/onboarding1.png
     - assets/images/onboarding2.png
     - assets/images/onboarding3.png
     - assets/images/on.png
     - assets/lottie/lottie.json
     - assets/atlas/KeralaBlankMap.svg
     - assets/atlas/KeralaMap.svg
     - assets/atlas/KeralaMapNew.svg
     - assets/images/logo.png



